-- insert mode
vim.keymap.set('i', '(', '()<Left>')
vim.keymap.set('i', '()', '()')
vim.keymap.set('i', '(<Enter>', '()<Left><CR><ESC><S-o>')

vim.keymap.set('i', '{', '{}<ESC>i')
vim.keymap.set('i', '{}', '{}')
vim.keymap.set('i', '{<Enter>', '{}<Left><CR><ESC><S-o>')

vim.keymap.set('i', '[', '[]<ESC>i')
vim.keymap.set('i', '[]', '[]')
vim.keymap.set('i', '[<Enter>', '[]<Left><CR><ESC><S-o>')

vim.keymap.set('i', '\'', '\'\'<Left>')
vim.keymap.set('i', '\'\'', '\'\'')
vim.keymap.set('i', '\'<Enter>', '\'<Left><CR><ESC><S-o>')

vim.keymap.set('i', '\"', '\"\"<Left>')
vim.keymap.set('i', '\"\"', '\"\"')
vim.keymap.set('i', '\"<Enter>', '\"<Left><CR><ESC><S-o>')

vim.keymap.set('i', 'jj', '<ESC>')

vim.keymap.set('i', '<expr><CR>', 'pumvisible() ? \"<C-y>\" : \"<CR>\"')
vim.keymap.set('i', '<expr><C-n>', 'pumvisible() ? \"<Down>\" : \"<C-n>\"')
vim.keymap.set('i', '<expr><C-p>', 'pumvisible() ? \"<Up>\" : \"<C-p>\"')


-- normal mode
vim.keymap.set('n', 'vt', '<cmd>vsplit<CR><cmd>terminal<CR>')
vim.keymap.set('n', '<C-n>', ':Fern . -reveal=% -drawer -toggle -width=40<CR>')
vim.keymap.set('n', 'J', '<Plug>AirlineSelectPrevTab')
vim.keymap.set('n', 'K', '<Plug>AirlineSelectNextTab')

-- term mode
vim.keymap.set('t', '<ESC>', '<C-\\><C-n>')
vim.keymap.set('t', '<C-W>n', '<cmd>new<cr>')
vim.keymap.set('t', '<C-W><C-N>', '<cmd>new<cr>')
vim.keymap.set('t', '<C-W>q', '<cmd>quit<cr>')
vim.keymap.set('t', '<C-W><C-Q>', '<cmd>quit<cr>')
vim.keymap.set('t', '<C-W>c', '<cmd>close<cr>')
vim.keymap.set('t', '<C-W>o', '<cmd>only<cr>')
vim.keymap.set('t', '<C-W><C-O>', '<cmd>only<cr>')
vim.keymap.set('t', '<C-W><Down>', '<cmd>wincmd j<cr>')
vim.keymap.set('t', '<C-W><C-J>', '<cmd>wincmd j<cr>')
vim.keymap.set('t', '<C-W>j', '<cmd>wincmd j<cr>')
vim.keymap.set('t', '<C-W><Up>', '<cmd>wincmd k<cr>')
vim.keymap.set('t', '<C-W><C-K>', '<cmd>wincmd k<cr>')
vim.keymap.set('t', '<C-W>k', '<cmd>wincmd k<cr>')
vim.keymap.set('t', '<C-W><Left>', '<cmd>wincmd h<cr>')
vim.keymap.set('t', '<C-W><C-H>', '<cmd>wincmd h<cr>')
vim.keymap.set('t', '<C-W><BS>', '<cmd>wincmd h<cr>')
vim.keymap.set('t', '<C-W>h', '<cmd>wincmd h<cr>')
vim.keymap.set('t', '<C-W><Right>', '<cmd>wincmd l<cr>')
vim.keymap.set('t', '<C-W><C-L>', '<cmd>wincmd l<cr>')
vim.keymap.set('t', '<C-W>l', '<cmd>wincmd l<cr>')
vim.keymap.set('t', '<C-W><C-W>', '<cmd>wincmd w<cr>')
vim.keymap.set('t', '<C-W>w', '<cmd>wincmd w<cr>')
vim.keymap.set('t', '<C-W>W', '<cmd>wincmd W<cr>')
vim.keymap.set('t', '<C-W>t', '<cmd>wincmd t<cr>')
vim.keymap.set('t', '<C-W><C-T>', '<cmd>wincmd t<cr>')
vim.keymap.set('t', '<C-W>b', '<cmd>wincmd b<cr>')
vim.keymap.set('t', '<C-W><C-B>', '<cmd>wincmd b<cr>')
vim.keymap.set('t', '<C-W>p', '<cmd>wincmd p<cr>')
vim.keymap.set('t', '<C-W><C-P>', '<cmd>wincmd p<cr>')
vim.keymap.set('t', '<C-W>P', '<cmd>wincmd P<cr>')
vim.keymap.set('t', '<C-W>r', '<cmd>wincmd r<cr>')
vim.keymap.set('t', '<C-W><C-R>', '<cmd>wincmd r<cr>')
vim.keymap.set('t', '<C-W>R', '<cmd>wincmd R<cr>')
vim.keymap.set('t', '<C-W>x', '<cmd>wincmd x<cr>')
vim.keymap.set('t', '<C-W><C-X>', '<cmd>wincmd x<cr>')
vim.keymap.set('t', '<C-W>K', '<cmd>wincmd K<cr>')
vim.keymap.set('t', '<C-W>J', '<cmd>wincmd J<cr>')
vim.keymap.set('t', '<C-W>H', '<cmd>wincmd H<cr>')
vim.keymap.set('t', '<C-W>L', '<cmd>wincmd L<cr>')
vim.keymap.set('t', '<C-W>T', '<cmd>wincmd T<cr>')
vim.keymap.set('t', '<C-W>=', '<cmd>wincmd =<cr>')
vim.keymap.set('t', '<C-W>-', '<cmd>wincmd -<cr>')
vim.keymap.set('t', '<C-W>+', '<cmd>wincmd +<cr>')
vim.keymap.set('t', '<C-W>z', '<cmd>pclose<cr>')
vim.keymap.set('t', '<C-W><C-Z>', '<cmd>pclose<cr>')
