memodir = "~/.memolist/memo"
editor = "nvim"
column = 20
width = 0
selectcmd = "fzf"
grepcmd = "grep -nH ${PATTERN} ${FILES}"
memotemplate = "~/.memolist/memotemplates/md.txt"
assetsdir = "."
pluginsdir = "~/dotfiles/.config/memo/plugins"
templatedirfile = ""
templatebodyfile = ""
